name: Best Site Ever
favicon: null
layout_spectrum: 0.5095
typography_spectrum: 0.2618
title: Best Site Ever
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d62621'
    - '#fbfcfd'
    - '#f5c67a'
    - '#2b2e50'
    - '#e5928e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
