name: Best Site Ever
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2618
title: Best Site Ever
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#ff3300'
    - '#ff2000'
    - '#000000'
    - '#ff0000'
  brandStrength: 0
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
