name: Best Site Ever
favicon: null
layout_spectrum: 0.25475
typography_spectrum: 0.2435
title: Best Site Ever
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f15c22'
    - '#efb39c'
    - '#201e1f'
    - '#8b8788'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
